# 1.Create a 3x3x3 array with random values using numpy



In [2]:
import numpy as np

random_array = np.random.rand(3, 3, 3)

print(random_array)

[[[0.84347875 0.64687224 0.4855029 ]
  [0.53681377 0.55323906 0.41506307]
  [0.91586327 0.26956409 0.02725277]]

 [[0.21461901 0.48895243 0.68162705]
  [0.13489498 0.86391498 0.89144177]
  [0.2419395  0.63497217 0.76230179]]

 [[0.86449786 0.81601202 0.69035884]
  [0.50795872 0.89698658 0.88805166]
  [0.08797857 0.73043688 0.49294838]]]


# 2.You can create a 5x5 matrix with values 1, 2, 3, and 4 just below the diagonal using NumPy like this:

In [4]:
matrix = np.zeros((5, 5), dtype=int)

values = [1, 2, 3, 4]
np.fill_diagonal(matrix[1:], values)

print(matrix)


[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


# 3.Create a 8*8 matrix and fill it with a checkboard pattern

In [7]:
import numpy as np

matrix = np.zeros((8, 8), dtype=int)

matrix[::2, ::2] = 1
matrix[1::2, 1::2] = 1

print(matrix)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


# 4.Normalize a 5*5 random matrix using numpy

In [8]:
import numpy as np

random = np.random.rand(5, 5)

Mean = np.mean(random)
Std = np.std(random)

normalized_matrix = (random - Mean) / Std

print("Original Matrix:")
print(random)

print("\nNormalized Matrix:")
print(normalized_matrix)


Original Matrix:
[[0.1481688  0.37200513 0.9186449  0.51259259 0.63538847]
 [0.95644211 0.61552743 0.37857761 0.26930341 0.26841994]
 [0.93267673 0.86729593 0.00228944 0.94565915 0.70147182]
 [0.00842645 0.51720544 0.7725248  0.52648339 0.48298083]
 [0.3004581  0.21778638 0.59649803 0.70852077 0.24850065]]

Normalized Matrix:
[[-1.29060633 -0.50556216  1.41162601 -0.01249043  0.41818224]
 [ 1.54418932  0.34852511 -0.48251099 -0.86576011 -0.86885863]
 [ 1.46083881  1.23153368 -1.80223793  1.50637105  0.64995137]
 [-1.78071405  0.00368789  0.89915009  0.03622772 -0.11634549]
 [-0.75649362 -1.04644187  0.28178477  0.67467361 -0.93872005]]


# 5. How to find common values between two arrays

In [11]:
array1 = np.array([7, 2, 1, 14, 5])
array2 = np.array([9, 4, 9, 6, 1])

common_values = np.intersect1d(array1, array2)
print(common_values)

[1]


# 6. How to get the dates of yestreday, today and tomorrow

In [12]:
from datetime import datetime, timedelta

today = datetime.now().date()

yesterday = today - timedelta(days=1)
tomorrow = today + timedelta(days=1)

print("Yesterday:", yesterday)
print("Today:", today)
print("Tomorrow:", tomorrow)


Yesterday: 2023-09-20
Today: 2023-09-21
Tomorrow: 2023-09-22


# 7. Consider two random array A and B, check if they are equal

In [13]:
import numpy as np

A = np.random.rand(5)
B = np.random.rand(5)

if np.array_equal(A, B):
    print("Arrays A and B are equal")
else:
    print("Arrays A and B are not equal")


Arrays A and B are not equal


# 8. Create random vector of size 10 and replace the minimum value nby zero using numpy

In [17]:
import numpy as np

random_vector = np.random.rand(10)
min_index = np.argmin(random_vector)

random_vector[min_index] = 0

print("Random Vector with Minimum Value Replaced:", random_vector)


Random Vector with Minimum Value Replaced: [0.58646723 0.88794572 0.38477633 0.         0.82781984 0.10403034
 0.18864928 0.05661105 0.60943035 0.99904938]


# 9.How to print all the values of an array using numpy

In [19]:
import numpy as np

my_array = np.array([1, 2, 3, 4, 5])

for i in my_array:
    print(i, end=" ")


1 2 3 4 5 

# 10. Subtract the mean of each row of a matrix

In [22]:
import numpy as np

matrix = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

row_means = np.mean(matrix, axis=1)

result_matrix = matrix - row_means.reshape(-1, 1)

print("Matrix:")
print(matrix)

print("\nMatrix with Row Means Subtracted:")
print(result_matrix)


Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix with Row Means Subtracted:
[[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]


# 11. Consider a given vector, how to add 1 to each  element indexed by a second vector (be careful with repeated indices)?

In [23]:
import numpy as np

given_vector = np.array([1, 2, 3, 4, 5])

index_vector = np.array([1, 3, 3, 0, 4])

result_vector = np.zeros_like(given_vector)

unique_indices = np.unique(index_vector)
for idx in unique_indices:
    result_vector[idx] = np.sum(given_vector[index_vector == idx]) + 1

print("Given Vector:", given_vector)
print("Index Vector:", index_vector)
print("Result Vector:", result_vector)


Given Vector: [1 2 3 4 5]
Index Vector: [1 3 3 0 4]
Result Vector: [5 2 0 6 6]


# 12.How to get the disgonal of dot product using numpy

In [25]:
import numpy as np

matrix1 = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

matrix2 = np.array([[4, 8, 7],
                    [6, 7, 14],
                    [3, 12, 11]])

dot_product = np.dot(matrix1, matrix2)

diagonal_elements = np.diag(dot_product)

print("Dot Product:")
print(dot_product)

print("\nDiagonal Elements:")
print(diagonal_elements)


Dot Product:
[[ 25  58  68]
 [ 64 139 164]
 [103 220 260]]

Diagonal Elements:
[ 25 139 260]


# 13. How to find the most frequent value in an array?

In [27]:
import numpy as np

x = np.random.randint(0, 10, 50)

frequent_value = np.bincount(x).argmax()

print("Array:")
print(x)
print("\nMost frequent value:", frequent_value)


Array:
[3 9 3 6 8 5 3 6 2 9 3 0 7 0 8 0 1 3 8 7 7 8 8 6 2 9 1 1 4 2 0 1 1 0 9 2 0
 3 7 4 9 8 0 7 2 0 3 3 9 3]

Most frequent value: 3


# 14. How to get the n largest values of an array

In [31]:
import numpy as np

arr = np.array([3, 1, 4, 1, 15, 9, 2, 6, 5, 3, 25])

n = int(input("Enter the n largest values You want in an array"))
largest_values = np.sort(arr)[-n:]

print("Original Array:", arr)

print(f"{n} Largest Values:", largest_values)


Enter the n largest values You want in an array4
Original Array: [ 3  1  4  1 15  9  2  6  5  3 25]
4 Largest Values: [ 6  9 15 25]


# 15. How to create a record array from a regular array

In [37]:
import numpy as np

regular_array = np.array([(111, 25, 100000),
                          (222, 30, 300000),
                          (333, 22, 160000)])

field_names = ["ID","Age","Salary"]

record_array = np.rec.fromarrays(regular_array.T, names=field_names)

print(record_array)


print("\nIDs:", record_array["ID"])
print("Ages:", record_array["Age"])
print("Salary:", record_array["Salary"])


[(111, 25, 100000) (222, 30, 300000) (333, 22, 160000)]

IDs: [111 222 333]
Ages: [25 30 22]
Salary: [100000 300000 160000]


# 16. How to swap two rows of an array?

In [40]:
import numpy as np

array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])
print("Original_Array")
print(array)

row1_index = 0  
row2_index = 2

array[[row1_index, row2_index]] = array[[row2_index, row1_index]]

print("Row Changed Array:")
print(array)


Original_Array
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Row Changed Array:
[[7 8 9]
 [4 5 6]
 [1 2 3]]


# 17. Write python code to reshape to the next dimension of numpy array

In [44]:
from numpy import array

Array=array([[23,34,121],[23,22,67],[686,434,123]])
reshaped_array=Array.reshape((Array.shape[0],Array.shape[1],1))
reshaped_array

array([[[ 23],
        [ 34],
        [121]],

       [[ 23],
        [ 22],
        [ 67]],

       [[686],
        [434],
        [123]]])

# Dataset Mini Case Study problems

In [3]:
np_olympic_country = np.array(['GBR', 'China', 'RUS', 'US', 'KOR', 'JPN', 'GER'])
np_olympic_country_gold = np.array([29, 38, 24, 46, 13, 7, 11])
np_olympic_country_silver = np.array([17, 28, 25, 28, 8, 14, 11])
np_olympic_country_bronze = np.array([19, 22, 32, 29, 7, 17, 14])

In [5]:
# Find the index of the maximum gold
max_gold_index = np.argmax(np_olympic_country_gold)
print("Country with Maximum Gold:", np_olympic_country[max_gold_index])


Country with Maximum Gold: US


In [9]:
# Find countries with more than 20 gold medals
countries_with_more_than_20_gold = np_olympic_country[np_olympic_country_gold > 20]
print("Countries with more than 20 Gold Medals:", countries_with_more_than_20_gold)


Countries with more than 20 Gold Medals: ['GBR' 'China' 'RUS' 'US']


In [ ]:
# Evaluate the dataset and print the medal information

In [7]:
for i in range(len(np_olympic_country)):
    print(f"{np_olympic_country[i]} - Gold Medals: {np_olympic_country_gold[i]}")

GBR - Gold Medals: 29
China - Gold Medals: 38
RUS - Gold Medals: 24
US - Gold Medals: 46
KOR - Gold Medals: 13
JPN - Gold Medals: 7
GER - Gold Medals: 11


In [8]:
total_medals = np_olympic_country_gold + np_olympic_country_silver + np_olympic_country_bronze
for i in range(len(np_olympic_country)):
    print(f"{np_olympic_country[i]} - Total Medals: {total_medals[i]}")

GBR - Total Medals: 65
China - Total Medals: 88
RUS - Total Medals: 81
US - Total Medals: 103
KOR - Total Medals: 28
JPN - Total Medals: 38
GER - Total Medals: 36
